Добавил тексты, как их предложил копирайтер
sf-pet-projects/androbot pull request #42
Opened 2021-03-23 06:10 UTC by rzabolotin

Сделал только для тех вьюшек которые более менее реализованы, к оставшимся вернусь когда они будут сделаны.
ну вернее сразу сделаю их по этому документу
https://docs.google.com/document/d/1zl2bWOfONEkxg8q-J1fiyN9qUoT-Q5T0BWmXg4f4sgQ/edit#

2021-03-23 06:10 UTC, churnikov commented
Task linked: [CU-fv4n8r Обновить тексты бота](https://app.clickup.com/t/fv4n8r)

2021-03-23 08:18 UTC, churnikov commented on templates/31_still_not_understand.md
> +ожалуйста, дайте нам знать, что именно было непонятно в формулировке вопроса. Это поможет сделать бота лучше. После этого у вас будет возможность посмотреть эталонный ответ и перейти к следующему воп
```suggestion
Пожалуйста, дайте нам знать, что именно было непонятно в формулировке вопроса. Это поможет сделать бота лучше. После этого у вас будет возможность посмотреть эталонный ответ и перейти к следующему вопросу.
```

2021-03-23 08:19 UTC, churnikov requested changes

2021-03-23 08:19 UTC, churnikov commented on templates/31_still_not_understand.md
>  👉 *Опиши, что вызвало затруднение при ответе на вопрос*
Наверно тогда "Опишите"

2021-03-23 08:19 UTC, churnikov commented on templates/05_select_answer_type.md
>  👉 *Выбери способ ответа*
```suggestion
👉 *Выберите способ ответа*
```
Тут и выше

2021-03-23 08:19 UTC, churnikov commented
И конфликты на до порезолвить

2021-03-24 00:35 UTC, rzabolotin commented
> И конфликты на до порезолвить

Спасибо, что внимательно почитал. Я что-то совсем не внимательно сделал.
Сейчас постарался все исправить.

а какие конфликты?

2021-03-24 08:53 UTC, churnikov commented
Про конфликты
![image](https://user-images.githubusercontent.com/8545082/112281789-812b9700-8c97-11eb-90d8-f31387f12610.png)

2021-03-24 09:35 UTC, churnikov approved these changes

2021-03-26 04:06 UTC, merged