добавил view user_score. когда кончаются все вопросы
sf-pet-projects/androbot pull request #47
Opened 2021-03-31 21:47 UTC by rzabolotin

2021-03-31 21:47 UTC, churnikov commented
Task linked: [CU-eax8fa Экран завершения сессии тестирования](https://app.clickup.com/t/eax8fa)

2021-04-01 09:19 UTC, churnikov commented on androbot/handlers.py
> +    Вопросы концились, покажем пользователю его оценку. Больше вопрос нет
```suggestion
    Вопросы кончились, покажем пользователю его оценку. Больше вопрос нет
```

2021-04-01 09:19 UTC, churnikov commented on templates/51_user_score.md
> +Это говорит о том, что {user_score_description}
Что-то я понял, что надо еще с Кристиной обсудить это

2021-04-02 15:22 UTC, churnikov commented on templates/51_user_score.md
> +Это говорит о том, что {user_score_description}
Мы пришли к тому, что этот этап не пропадает, но Кристине надо еще немного подумать над текстами. Она обещала вернутся с ответом в понедельник

2021-04-09 13:09 UTC, churnikov commented on templates/51_user_score.md
> +Это говорит о том, что {user_score_description}
Там в доке подвезли тексты
```
🎉 Поздравляю, тест завершен! Давайте посмотрим, что получилось:
Ваша оценка: Х
Это говорит о том, что…
X = 100-85, то
“Поздравляем! Вы готовы к прохождению технического собеседования! Самое время опубликовать резюме, откликнуться на пару вакансий и двигаться вперед к своим целям.”
X = 85-70, то
“Отличный результат. Мы рекомендуем вам пройтись еще раз по верхам, решить пару общих практических задач и смело публиковать резюме для прохождения технических собеседований. Вперед к мечте!”
X = 70-0, то
“Хороший результат. Мы рекомендуем повторить все основные темы, отдельно по каждой решить пару практических задач и освежить основные знания теории. А потом вернуться к нашему боту еще раз. Будем вас ждать :) ”
👉 **Выберите, что делать дальше**
👍 Оценить бота
🏠 Главное меню
```

Там в базе будет 3 варианта самооценки: правильно, частично правильно, неправильно.
Надо будет кидать туда запрос на получение оценок и считать правильно как 1 балл, частично 0.5, неправильно 0, затем нормировать и выдавать результат как выше описано

2021-04-11 09:30 UTC, churnikov requested changes

2021-04-11 09:30 UTC, churnikov commented on androbot/views.py
> +        additional_info = "Материалы для повторения...\n{}\n".format(additional_info)
А чего не так:
```suggestion
    else:
        additional_info = f"Материалы для повторения...\n{additional_info}\n"
```

2021-04-11 09:30 UTC, churnikov commented on templates/51_user_score.md
> +Это говорит о том, что {user_score_description}
Сделаешь это?)

2021-04-19 09:31 UTC, churnikov commented on androbot/actions.py
> +        crud.remove_train_materials(self.db, user.tg_user_id)
Ну подожди
Тебе не кажется странным удалять обучающие материалы?

2021-04-19 09:31 UTC, churnikov commented on androbot/actions.py
> +        crud.remove_train_materials(self.db, user.tg_user_id)
И вообще, мне казалось мы пришли всё же к тому чтобы не удалять сессии, а создавать новые, нет?

2021-04-19 09:53 UTC, rzabolotin commented on androbot/actions.py
> +        crud.remove_train_materials(self.db, user.tg_user_id)
Это не обучаюший материал, это признак того, что пользователь запросил доп.материал
Ну когда будут новые сессии тогда да, а пока мы ее удаляем. то эти признаки тоже надо удалять.
а то в другой сессии он только начал отвечать, а уже хвост запросов доп.материалов из прошлой передается

2021-04-19 09:53 UTC, rzabolotin commented on androbot/actions.py
> +        crud.remove_train_materials(self.db, user.tg_user_id)
ответы же удаляем

2021-04-19 12:35 UTC, churnikov commented on androbot/actions.py
> +        crud.remove_train_materials(self.db, user.tg_user_id)
мы в бд добавили session id и в таблицу с ответами. Так что теперь удалять ответы не надо

https://app.clickup.com/t/gt3tgw

2021-04-20 01:00 UTC, rzabolotin commented on androbot/views.py
> +        additional_info = "Материалы для повторения...\n{}\n".format(additional_info)
ок, пропустил это замечание

2021-04-21 01:13 UTC, rzabolotin commented on androbot/actions.py
> +        crud.remove_train_materials(self.db, user.tg_user_id)
в другом ПР сделаю

2021-04-21 01:14 UTC, rzabolotin commented on templates/51_user_score.md
> +Это говорит о том, что {user_score_description}
сделал

2021-04-21 05:21 UTC, churnikov approved these changes

2021-04-21 05:45 UTC, merged