CU-fv89jy-Victoria-Shepard
sf-pet-projects/androbot pull request #48
Opened 2021-04-04 19:30 UTC by demonolock

2021-04-04 19:30 UTC, demonolock commented
Task linked: [CU-fv89jy Реализовать функцию add_train_materials](https://app.clickup.com/t/fv89jy)

2021-04-06 11:00 UTC, churnikov requested changes

2021-04-06 11:00 UTC, churnikov commented on androbot/tests.py
>          act.remove_user(db_user)
Ты уверена?
act выйдя из with закроется и там подключение к бд должно закрыться.
Вообще, это кажется стоит [фикстурой оформить](https://docs.pytest.org/en/stable/fixture.html#back-to-fixtures)

2021-04-06 11:00 UTC, churnikov commented on androbot/tests.py
>          act.remove_user(db_user)
Ну и подобные этому блоки кода тоже

2021-04-06 11:00 UTC, churnikov commented on androbot/crud.py
> +    db.refresh(data)
👍🏻

2021-04-06 11:00 UTC, churnikov commented on androbot/actions.py
> +    def remove_train_material(self, tg_user_id: int, question_id: int) -> None:
Честно говоря, было бы супер, если ты допишешь пару слов в документацию к функциям, пожалуйста)

2021-04-08 18:22 UTC, demonolock commented on androbot/actions.py
> +    def remove_train_material(self, tg_user_id: int, question_id: int) -> None:
Добавила комменты

2021-04-09 08:31 UTC, churnikov requested changes

2021-04-09 08:31 UTC, churnikov commented on androbot/tests.py
> +    act.remove_user(db_user)
Так подожди, тебе бы таб добавить (тут и вообще)
У тебя же act все контекста with, а потому будет некорректно работать
Когда мы из with выходим вызывается `__exit__`
https://github.com/sf-pet-projects/androbot/blob/5e97365a1e3d3026d32fd868e0befffbe796a43f/androbot/actions.py#L31
А потому у тебя тут уже закрыто подключение к бд

2021-04-11 06:00 UTC, rzabolotin commented
1)Additional info - это таблица куда заносим признак того, что пользователь запросил доп.материалы к вопросу?

2) Поля с названием review_type - что содержат? что туда нужно передавать? не понятно.

3) С комментариям, отлично! Молодец! Можно еще в actions добавить? я больше с actions работаю, а не с crud.

4) Можешь добавить меод get_question_scores - который бы вернул все оценки пользователя (сейчас все, но если мы будем делать сессии то потом сделать отбор по сессии)

2021-04-11 09:26 UTC, churnikov commented
> Additional info - это таблица куда заносим признак того, что пользователь запросил доп.материалы к вопросу?

Да, это таблица соответствия user, доп. инфа

> Поля с названием review_type - что содержат? что туда нужно передавать? не понятно.
Это как тип ответа у нас, т.е. может быть текстом или голосом

> С комментариям, отлично! Молодец! Можно еще в actions добавить? я больше с actions работаю, а не с crud
Я однозначно за

2021-04-11 10:28 UTC, churnikov requested changes

2021-04-11 10:28 UTC, churnikov commented on androbot/tests.py
> +    return Actions()
Не совсем правильно

Надо так
```suggestion
@pytest.fixture()
def act():
    action = Actions()
    yield action
    action.__close__()
```

Дело в том, что все что определено до yield включительно, будет выполнено перед тестом, а то что после yield, независимо от успеха теста, после его выполнения

2021-04-11 10:34 UTC, churnikov approved these changes

2021-04-11 11:11 UTC, merged